"""Add Learning APIs

Revision ID: 01e82db7edb8
Revises: e69f0951f55b
Create Date: 2025-08-26 14:52:18.912186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e82db7edb8'
down_revision: Union[str, None] = 'e69f0951f55b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('how_to_guides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_how_to_guides_id'), 'how_to_guides', ['id'], unique=False)
    op.create_index(op.f('ix_how_to_guides_title'), 'how_to_guides', ['title'], unique=False)
    op.create_table('latest_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_latest_updates_id'), 'latest_updates', ['id'], unique=False)
    op.create_index(op.f('ix_latest_updates_title'), 'latest_updates', ['title'], unique=False)
    op.create_table('video_tutorials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_tutorials_id'), 'video_tutorials', ['id'], unique=False)
    op.create_index(op.f('ix_video_tutorials_title'), 'video_tutorials', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_tutorials_title'), table_name='video_tutorials')
    op.drop_index(op.f('ix_video_tutorials_id'), table_name='video_tutorials')
    op.drop_table('video_tutorials')
    op.drop_index(op.f('ix_latest_updates_title'), table_name='latest_updates')
    op.drop_index(op.f('ix_latest_updates_id'), table_name='latest_updates')
    op.drop_table('latest_updates')
    op.drop_index(op.f('ix_how_to_guides_title'), table_name='how_to_guides')
    op.drop_index(op.f('ix_how_to_guides_id'), table_name='how_to_guides')
    op.drop_table('how_to_guides')
    # ### end Alembic commands ###
