"""Update Loan Models

Revision ID: 0406d474b10a
Revises: c3293678ebd2
Create Date: 2025-08-11 11:40:21.666810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0406d474b10a'
down_revision: Union[str, None] = 'c3293678ebd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

loan_repayment_status_enum = sa.Enum(
    'PENDING',
    'PAID',
    'OVERDUE',
    name='loanrepaymentstatus'
)
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    loan_repayment_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('loan_repayments', sa.Column('status', loan_repayment_status_enum, nullable=True))
    op.add_column('loans', sa.Column('emi_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'emi_number')
    op.drop_column('loan_repayments', 'status')
    # ### end Alembic commands ###
