"""Update User Role and User order

Revision ID: 0a5e7832a364
Revises: a7de983e7e40
Create Date: 2025-07-16 02:26:51.017294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a5e7832a364'
down_revision: Union[str, None] = 'a7de983e7e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_orders', sa.Column('business_id', sa.Integer(), nullable=True))
    op.add_column('user_orders', sa.Column('order_type', sa.String(), nullable=True))
    op.add_column('user_orders', sa.Column('notes', sa.String(), nullable=True))
    op.alter_column('user_orders', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'user_orders', 'businesses', ['business_id'], ['id'])
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'user_orders', type_='foreignkey')
    op.alter_column('user_orders', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_orders', 'notes')
    op.drop_column('user_orders', 'order_type')
    op.drop_column('user_orders', 'business_id')
    # ### end Alembic commands ###
