"""Added Offer,Combo and Banner Module

Revision ID: 0f1f33b1e329
Revises: 81e3bbad0d99
Create Date: 2025-07-25 01:30:22.679864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f1f33b1e329'
down_revision: Union[str, None] = '81e3bbad0d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('title', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('link_type', sa.Enum('PRODUCT', 'SERVICE', 'CATEGORY', 'COMBO', 'OFFER', 'EXTERNAL', name='bannerlinktype'), nullable=True),
    sa.Column('link_target_id', sa.Integer(), nullable=True),
    sa.Column('external_url', sa.String(), nullable=True),
    sa.Column('position', sa.Enum('HOMEPAGE', 'CATEGORY_PAGE', 'SERVICE_PAGE', 'OFFER_ZONE', 'POPUP', 'TOP_BAR', name='bannerposition'), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('combo_price', sa.Float(), nullable=False),
    sa.Column('discount_type', sa.String(), nullable=True),
    sa.Column('discount_value', sa.Float(), nullable=True),
    sa.Column('max_discount', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('offer_type', sa.Enum('FLAT_DISCOUNT', 'PERCENTAGE_DISCOUNT', 'BUY_X_GET_Y', 'BUNDLE_PRICING', 'CART_VALUE_BASED', 'CUSTOMER_BASED', 'SERVICE_DISCOUNT', 'TIME_LIMITED', name='offertype'), nullable=False),
    sa.Column('auto_apply', sa.Boolean(), nullable=True),
    sa.Column('can_stack_with_coupon', sa.Boolean(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('available_limit', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combo_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('combo_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('PRODUCT', 'SERVICE', name='combotype'), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['combo_id'], ['combos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('condition_type', sa.Enum('PRODUCT', 'SERVICE', 'CATEGORY', 'CART_TOTAL', 'USER_TAG', 'FIRST_ORDER', 'CUSTOMER_ID', 'TIME_WINDOW', 'PAYMENT_METHOD', name='offerconditiontype'), nullable=False),
    sa.Column('operator', sa.Enum('EQUALS', 'IN', 'NOT_IN', 'GTE', 'LTE', 'BETWEEN', name='conditionoperator'), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.Enum('FLAT', 'PERCENTAGE', 'FREE_PRODUCT', 'DISCOUNTED_PRODUCT', 'FREE_SERVICE', 'DISCOUNTED_SERVICE', 'CASHBACK', 'FREE_SHIPPING', name='offerrewardtype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('item_type', sa.String(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('max_discount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_rewards')
    op.drop_table('offer_conditions')
    op.drop_table('combo_items')
    op.drop_table('offers')
    op.drop_table('combos')
    op.drop_table('banners')
    # ### end Alembic commands ###
