"""Add User Adding Functionalty

Revision ID: 172d974df748
Revises: 55cb4298ea48
Create Date: 2025-08-22 19:35:15.230923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172d974df748'
down_revision: Union[str, None] = '55cb4298ea48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('extra_users', sa.Integer(), nullable=True))
    op.add_column('user_orders', sa.Column('extra_users', sa.Integer(), nullable=True))
    op.add_column('user_orders', sa.Column('pro_rata_days', sa.Integer(), nullable=True))
    op.add_column('user_orders', sa.Column('per_user_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_orders', 'per_user_price')
    op.drop_column('user_orders', 'pro_rata_days')
    op.drop_column('user_orders', 'extra_users')
    op.drop_column('businesses', 'extra_users')
    # ### end Alembic commands ###
