"""Update Contact Models and Table

Revision ID: 18adaded97c9
Revises: 3db663583c8d
Create Date: 2025-07-09 22:02:19.574339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18adaded97c9'
down_revision: Union[str, None] = '3db663583c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_contacts', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('business_contacts', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_column('contacts', 'first_name')
    op.drop_column('contacts', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('business_contacts', 'last_name')
    op.drop_column('business_contacts', 'first_name')
    # ### end Alembic commands ###
