"""Update Product and Service Tables 

Revision ID: 20304b0a7615
Revises: 8637ca9b5e05
Create Date: 2025-07-13 22:33:55.949617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20304b0a7615'
down_revision: Union[str, None] = '8637ca9b5e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'tax_value')
    op.drop_column('product_variants', 'include_tax')
    op.add_column('products', sa.Column('include_tax', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('tax_value', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'tax_value')
    op.drop_column('products', 'include_tax')
    op.add_column('product_variants', sa.Column('include_tax', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('product_variants', sa.Column('tax_value', sa.NUMERIC(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
