"""Update Loan Table

Revision ID: 222cb81c4a57
Revises: fc019811c6d4
Create Date: 2025-08-08 18:25:20.649203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222cb81c4a57'
down_revision: Union[str, None] = 'fc019811c6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('repayment_day', sa.Integer(), nullable=True))
    op.drop_column('loans', 'repayment_day_of_month')
    op.drop_column('loans', 'repayment_day_of_week')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('repayment_day_of_week', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('loans', sa.Column('repayment_day_of_month', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('loans', 'repayment_day')
    # ### end Alembic commands ###
