"""Update Cart/Order

Revision ID: 22fa7162039e
Revises: fc0d4a2c2968
Create Date: 2025-08-01 03:24:16.154019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22fa7162039e'
down_revision: Union[str, None] = 'fc0d4a2c2968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_contact_ledgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('business_contact_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_contact_id'], ['business_contacts.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('order_payments', 'payment_gateway',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order_payments', 'gateway_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('orders', sa.Column('cart_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'cart_id')
    op.alter_column('order_payments', 'gateway_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('order_payments', 'payment_gateway',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('business_contact_ledgers')
    # ### end Alembic commands ###
