"""Add Product tables

Revision ID: 251a96b986aa
Revises: df4d79a97833
Create Date: 2025-06-25 23:41:32.264655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251a96b986aa'
down_revision: Union[str, None] = 'df4d79a97833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('business_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'businesses', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'business_id')
    # ### end Alembic commands ###
