"""Update Product and Service Tables 

Revision ID: 2ec202148343
Revises: bfbfc1889e9b
Create Date: 2025-07-13 22:13:49.957418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ec202148343'
down_revision: Union[str, None] = 'bfbfc1889e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('include_tax', sa.Boolean(), nullable=True))
    op.add_column('product_variants', sa.Column('tax_value', sa.Numeric(), nullable=True))
    op.add_column('service_schedules', sa.Column('buffer_time_before', sa.Integer(), nullable=True, comment='Minutes before service for setup/preparation.'))
    op.add_column('service_schedules', sa.Column('buffer_time_after', sa.Integer(), nullable=True, comment='Minutes after service for cleanup/transition.'))
    op.add_column('service_schedules', sa.Column('lead_time', sa.Integer(), nullable=True, comment='Minimum advance time (in minutes) required for booking.'))
    op.add_column('service_schedules', sa.Column('recurring', sa.Boolean(), nullable=True, comment='True if the schedule repeats regularly (recurring).'))
    op.add_column('services', sa.Column('include_tax', sa.Boolean(), nullable=True))
    op.add_column('services', sa.Column('tax_value', sa.Numeric(), nullable=True))
    op.add_column('services', sa.Column('additional_fees', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('services', sa.Column('location_type', sa.String(), nullable=True, comment="Service location type: 'onsite', 'online', or 'customer_location'."))
    op.add_column('services', sa.Column('capacity', sa.Integer(), nullable=True, comment='Maximum number of people per booking (group services/classes).'))
    op.add_column('services', sa.Column('booking_required', sa.Boolean(), nullable=True, comment='True if booking is required; False allows walk-ins.'))
    op.add_column('services', sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Custom, business-specific fields (flexible JSON).'))
    op.add_column('services', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('services', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('services', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('cancellation_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'cancellation_policy')
    op.drop_column('services', 'duration_minutes')
    op.drop_column('services', 'is_featured')
    op.drop_column('services', 'tags')
    op.drop_column('services', 'custom_fields')
    op.drop_column('services', 'booking_required')
    op.drop_column('services', 'capacity')
    op.drop_column('services', 'location_type')
    op.drop_column('services', 'additional_fees')
    op.drop_column('services', 'tax_value')
    op.drop_column('services', 'include_tax')
    op.drop_column('service_schedules', 'recurring')
    op.drop_column('service_schedules', 'lead_time')
    op.drop_column('service_schedules', 'buffer_time_after')
    op.drop_column('service_schedules', 'buffer_time_before')
    op.drop_column('product_variants', 'tax_value')
    op.drop_column('product_variants', 'include_tax')
    # ### end Alembic commands ###
