"""Update Product and Login

Revision ID: 344ea55ab726
Revises: dfe6d79a6c42
Create Date: 2025-08-14 11:30:16.304079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '344ea55ab726'
down_revision: Union[str, None] = 'dfe6d79a6c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_code', sa.String(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('packed_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_batches_is_expired'), 'product_batches', ['is_expired'], unique=False)
    op.create_table('product_pack_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('pack_quantity', sa.Integer(), nullable=False),
    sa.Column('additional_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product_master_data')
    op.add_column('product_stock_logs', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.add_column('product_stock_logs', sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('product_stock_logs', sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_index('ix_product_stock_logs_id', table_name='product_stock_logs')
    op.create_foreign_key(None, 'product_stock_logs', 'product_batches', ['batch_id'], ['id'])
    op.add_column('products', sa.Column('is_variant', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('qrcode', sa.String(), nullable=True))
    op.add_column('products', sa.Column('unit_weight', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('unit_volume', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('origin_country', sa.String(length=10), nullable=True))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('products', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'base_unit',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('products', 'package_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('products', 'hsn_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_index('ix_products_id', table_name='products')
    op.create_unique_constraint(None, 'products', ['qrcode'])
    op.create_unique_constraint(None, 'products', ['image_url'])
    op.drop_column('products', 'expiry_date')
    op.drop_column('products', 'purchase_price')
    op.drop_column('products', 'packed_date')
    op.drop_column('products', 'qr_code')
    op.drop_column('products', 'is_product_variant')
    op.drop_column('products', 'stock_qty')
    op.add_column('user_otps', sa.Column('isd_code', sa.String(), nullable=True))
    op.add_column('user_otps', sa.Column('phone_number', sa.String(), nullable=True))
    op.drop_column('users', 'whatsapp_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('whatsapp_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_column('user_otps', 'phone_number')
    op.drop_column('user_otps', 'isd_code')
    op.add_column('products', sa.Column('stock_qty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('is_product_variant', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('qr_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('packed_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('purchase_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    op.alter_column('products', 'hsn_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('products', 'package_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('products', 'base_unit',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('products', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('products', 'origin_country')
    op.drop_column('products', 'dimensions')
    op.drop_column('products', 'unit_volume')
    op.drop_column('products', 'unit_weight')
    op.drop_column('products', 'qrcode')
    op.drop_column('products', 'is_variant')
    op.drop_constraint(None, 'product_stock_logs', type_='foreignkey')
    op.create_index('ix_product_stock_logs_id', 'product_stock_logs', ['id'], unique=False)
    op.drop_column('product_stock_logs', 'total_amount')
    op.drop_column('product_stock_logs', 'unit_price')
    op.drop_column('product_stock_logs', 'batch_id')
    op.create_table('product_master_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('base_unit', 'package_type', 'brand', 'manufacturer', name='master_type'), autoincrement=False, nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name='product_master_data_business_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_master_data_pkey')
    )
    op.drop_table('product_pack_options')
    op.drop_index(op.f('ix_product_batches_is_expired'), table_name='product_batches')
    op.drop_table('product_batches')
    # ### end Alembic commands ###
