"""Update Coupon Table

Revision ID: 4c90b0ea97ef
Revises: 2e6ff5af1c69
Create Date: 2025-07-21 19:01:56.925708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c90b0ea97ef'
down_revision: Union[str, None] = '2e6ff5af1c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('label', sa.String(), nullable=False))
    op.add_column('coupons', sa.Column('description', sa.String(), nullable=False))
    op.add_column('coupons', sa.Column('max_discount_amount', sa.Float(), nullable=True))
    op.add_column('coupons', sa.Column('min_cart_value', sa.Float(), nullable=False))
    op.add_column('coupons', sa.Column('available_limit', sa.Integer(), nullable=True))
    op.add_column('coupons', sa.Column('applied_count', sa.Integer(), nullable=False))
    op.add_column('coupons', sa.Column('is_auto_applied', sa.Boolean(), nullable=True))
    op.add_column('coupons', sa.Column('exclude_product_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('coupons', sa.Column('exclude_service_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'exclude_service_ids')
    op.drop_column('coupons', 'exclude_product_ids')
    op.drop_column('coupons', 'is_auto_applied')
    op.drop_column('coupons', 'applied_count')
    op.drop_column('coupons', 'available_limit')
    op.drop_column('coupons', 'min_cart_value')
    op.drop_column('coupons', 'max_discount_amount')
    op.drop_column('coupons', 'description')
    op.drop_column('coupons', 'label')
    # ### end Alembic commands ###
