"""Add motivation quotes

Revision ID: 55a5868b7e1c
Revises: 5137205ae2fd
Create Date: 2025-08-18 23:27:20.860155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a5868b7e1c'
down_revision: Union[str, None] = '5137205ae2fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_motivations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quote_en', sa.String(length=1000), nullable=False),
    sa.Column('quote_hi', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_index(op.f('ix_daily_motivations_id'), 'daily_motivations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_motivations_id'), table_name='daily_motivations')
    op.drop_table('daily_motivations')
    # ### end Alembic commands ###
