"""Update Multi Lingual Data

Revision ID: 57485a7c181b
Revises: 0f1f33b1e329
Create Date: 2025-07-27 00:04:22.653790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57485a7c181b'
down_revision: Union[str, None] = '0f1f33b1e329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('banners', 'title',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.execute("""
        UPDATE banners
        SET 
            title = title::jsonb->>'en'
    """)
    
    op.alter_column('categories', 'name',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.execute("""
        UPDATE categories
        SET 
            name = name::jsonb->>'en'
    """)
    
    #Combo Upgrade
    op.alter_column('combos', 'name',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('combos', 'description',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.execute("""
        UPDATE combos
        SET 
            name = name::jsonb->>'en',
            description = description::jsonb->>'en'
    """)
    
    op.add_column('coupons', sa.Column('terms_condition', sa.String(length=2000), nullable=True))
    
    # Step 1: Add new columns
    op.add_column('faqs', sa.Column('question', sa.String(length=500), nullable=True))
    op.add_column('faqs', sa.Column('answer', sa.String(length=2000), nullable=True))

    # Step 2: Populate new columns from JSON (extract "en" language)
    op.execute("""
        UPDATE faqs
        SET
            question = content::jsonb #>
                '{translations,0,question}',
            answer = content::jsonb #>
                '{translations,0,answer}'
        WHERE content::jsonb @> '{"translations": [{"language": "en"}]}';
    """)
    # Step 3: Make new columns non-nullable (after data is migrated)
    op.alter_column('faqs', 'question', existing_type=sa.String(length=500), nullable=False)
    op.alter_column('faqs', 'answer', existing_type=sa.String(length=2000), nullable=False)
    op.drop_column('faqs', 'content')

    #Offer Upgrade
    op.alter_column('offers', 'name',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('offers', 'description',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.execute("""
        UPDATE offers
        SET 
            name = name::jsonb->>'en',
            description = description::jsonb->>'en'
    """)
    
    #Product Upgrade
    op.alter_column('products', 'name',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.execute("""
        UPDATE products
        SET 
            name = name::jsonb->>'en',
            description = description::jsonb->>'en'
    """)
    
    # Service Upgrade
    op.alter_column('services', 'name',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('services', 'description',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('services', 'cancellation_policy',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.execute("""
        UPDATE services
        SET 
            name = name::jsonb->>'en',
            description = description::jsonb->>'en',
            cancellation_policy = cancellation_policy::jsonb->>'en'
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'cancellation_policy',
               existing_type=sa.String(length=1000),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('services', 'description',
               existing_type=sa.String(length=1000),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('services', 'name',
               existing_type=sa.String(length=100),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.String(length=1000),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.String(length=100),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('offers', 'description',
               existing_type=sa.String(length=2000),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('offers', 'name',
               existing_type=sa.String(length=100),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.add_column('faqs', sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('faqs', 'answer')
    op.drop_column('faqs', 'question')
    op.drop_column('coupons', 'terms_condition')
    op.alter_column('combos', 'description',
               existing_type=sa.String(length=2000),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('combos', 'name',
               existing_type=sa.String(length=100),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('categories', 'name',
               existing_type=sa.String(length=100),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('banners', 'title',
               existing_type=sa.String(length=100),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
