"""Update Cart/Order

Revision ID: 60db0098bb75
Revises: 9f0479bf9617
Create Date: 2025-07-31 23:57:31.171828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60db0098bb75'
down_revision: Union[str, None] = '9f0479bf9617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('coupon_removed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'coupon_removed')
    # ### end Alembic commands ###
