"""Add User Tour

Revision ID: 6f39296bb7a9
Revises: 7b12d3af5516
Create Date: 2025-08-15 20:23:50.631842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f39296bb7a9'
down_revision: Union[str, None] = '7b12d3af5516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tour_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tour_key', sa.String(length=50), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tour_key', name='unique_user_tour')
    )
    op.create_index(op.f('ix_user_tour_progress_id'), 'user_tour_progress', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tour_progress_id'), table_name='user_tour_progress')
    op.drop_table('user_tour_progress')
    # ### end Alembic commands ###
