"""Alter Import Job for more specific details

Revision ID: 77192bc6247f
Revises: ac1b7d5c8fb1
Create Date: 2026-02-09 19:24:08.651879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77192bc6247f'
down_revision: Union[str, None] = 'ac1b7d5c8fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_jobs', sa.Column('skipped_rows', sa.Integer(), nullable=True))
    op.add_column('import_jobs', sa.Column('duplicate_rows', sa.Integer(), nullable=True))
    op.add_column('import_jobs', sa.Column('invalid_rows', sa.Integer(), nullable=True))
    op.add_column('import_jobs', sa.Column('meta', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_jobs', 'meta')
    op.drop_column('import_jobs', 'invalid_rows')
    op.drop_column('import_jobs', 'duplicate_rows')
    op.drop_column('import_jobs', 'skipped_rows')
    # ### end Alembic commands ###
