"""Add Permissions Tables

Revision ID: 77d4e8196e00
Revises: 0d7851799738
Create Date: 2025-06-12 19:18:15.748810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d4e8196e00'
down_revision: Union[str, None] = '0d7851799738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('business_key', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'businesses', ['business_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'businesses', type_='unique')
    op.drop_column('businesses', 'business_key')
    # ### end Alembic commands ###
