"""Update Business and Order Tables

Revision ID: 82b5a80c0fd1
Revises: d3b8afbebb44
Create Date: 2025-08-06 23:24:33.650773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b5a80c0fd1'
down_revision: Union[str, None] = 'd3b8afbebb44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_contacts', sa.Column('address_line1', sa.String(), nullable=True))
    op.add_column('business_contacts', sa.Column('address_line2', sa.String(), nullable=True))
    op.add_column('business_contacts', sa.Column('city', sa.String(), nullable=True))
    op.add_column('business_contacts', sa.Column('state', sa.String(), nullable=True))
    op.add_column('business_contacts', sa.Column('country', sa.String(), nullable=True))
    op.add_column('business_contacts', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('isd_code', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('email', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('website', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('term_conditions', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('privacy_policy', sa.String(), nullable=True))
    op.add_column('order_payments', sa.Column('transaction_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_order_payments_transaction_id'), 'order_payments', ['transaction_id'], unique=True)
    op.add_column('orders', sa.Column('invoice_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('invoice_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_orders_invoice_number'), 'orders', ['invoice_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_invoice_number'), table_name='orders')
    op.drop_column('orders', 'invoice_url')
    op.drop_column('orders', 'invoice_number')
    op.drop_index(op.f('ix_order_payments_transaction_id'), table_name='order_payments')
    op.drop_column('order_payments', 'transaction_id')
    op.drop_column('businesses', 'privacy_policy')
    op.drop_column('businesses', 'term_conditions')
    op.drop_column('businesses', 'notes')
    op.drop_column('businesses', 'website')
    op.drop_column('businesses', 'email')
    op.drop_column('businesses', 'phone_number')
    op.drop_column('businesses', 'isd_code')
    op.drop_column('business_contacts', 'postal_code')
    op.drop_column('business_contacts', 'country')
    op.drop_column('business_contacts', 'state')
    op.drop_column('business_contacts', 'city')
    op.drop_column('business_contacts', 'address_line2')
    op.drop_column('business_contacts', 'address_line1')
    # ### end Alembic commands ###
