"""Restructure Tables

Revision ID: 8dcae42d723b
Revises: e2b04cebafc8
Create Date: 2025-07-05 16:24:49.327770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dcae42d723b'
down_revision: Union[str, None] = 'e2b04cebafc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('services', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_constraint('users_phone_number_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_phone_number_key', 'users', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('services', 'is_deleted')
    op.drop_column('products', 'is_deleted')
    # ### end Alembic commands ###
