"""Add Cart/Order Tables

Revision ID: 8df70738323c
Revises: 4942337aa424
Create Date: 2025-07-30 17:48:52.760562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df70738323c'
down_revision: Union[str, None] = '4942337aa424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('business_contact_id', sa.UUID(), nullable=False),
    sa.Column('anonymous_id', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('WEB', 'BACK_OFFICE', name='cartordersource'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_contact_id'], ['business_contacts.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_business_contact_id'), 'carts', ['business_contact_id'], unique=False)
    op.create_index(op.f('ix_carts_business_id'), 'carts', ['business_id'], unique=False)
    op.create_index(op.f('ix_carts_id'), 'carts', ['id'], unique=False)
    op.create_index(op.f('ix_carts_source'), 'carts', ['source'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('business_contact_id', sa.UUID(), nullable=True),
    sa.Column('anonymous_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('WEB', 'BACK_OFFICE', name='cartordersource'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_status', sa.Enum('PENDING', 'PLACED', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'COMPLETED', name='cartorderstatus'), nullable=False),
    sa.Column('is_delivery', sa.Boolean(), nullable=False),
    sa.Column('is_online_payment', sa.Boolean(), nullable=False),
    sa.Column('payment_mode', sa.Enum('OFFLINE', 'ONLINE', name='orderpaymentmode'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_contact_id'], ['business_contacts.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_business_contact_id'), 'orders', ['business_contact_id'], unique=False)
    op.create_index(op.f('ix_orders_business_id'), 'orders', ['business_id'], unique=False)
    op.create_index(op.f('ix_orders_created_by_user_id'), 'orders', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_order_status'), 'orders', ['order_status'], unique=False)
    op.create_index(op.f('ix_orders_source'), 'orders', ['source'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('actual_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('time_slot', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.create_table('order_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('initiated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('initiated_by_role', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_action_logs_order_id'), 'order_action_logs', ['order_id'], unique=False)
    op.create_table('order_delivery_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('delivery_type', sa.String(), nullable=False),
    sa.Column('address_line1', sa.String(), nullable=False),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('scheduled_time_slot', sa.String(), nullable=True),
    sa.Column('estimated_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_delivery_details_delivery_status'), 'order_delivery_details', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_order_delivery_details_order_id'), 'order_delivery_details', ['order_id'], unique=True)
    op.create_table('order_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_gateway', sa.String(), nullable=False),
    sa.Column('payment_reference_id', sa.String(), nullable=True),
    sa.Column('payment_method', sa.Enum('UPI', 'CARD', 'NETBANKING', 'WALLET', 'CASH', name='orderpaymentmethod'), nullable=False),
    sa.Column('gateway_status', sa.String(), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='orderpaymentstatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('gateway_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('receipt_url', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', name='uq_order_payment_order_id')
    )
    op.create_index(op.f('ix_order_payments_order_id'), 'order_payments', ['order_id'], unique=False)
    op.create_index('ix_order_payments_order_id_status', 'order_payments', ['order_id', 'payment_status'], unique=False)
    op.create_index(op.f('ix_order_payments_payment_status'), 'order_payments', ['payment_status'], unique=False)
    op.create_table('order_status_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('changed_by_role', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_logs_order_id'), 'order_status_logs', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_status_logs_order_id'), table_name='order_status_logs')
    op.drop_table('order_status_logs')
    op.drop_index(op.f('ix_order_payments_payment_status'), table_name='order_payments')
    op.drop_index('ix_order_payments_order_id_status', table_name='order_payments')
    op.drop_index(op.f('ix_order_payments_order_id'), table_name='order_payments')
    op.drop_table('order_payments')
    op.drop_index(op.f('ix_order_delivery_details_order_id'), table_name='order_delivery_details')
    op.drop_index(op.f('ix_order_delivery_details_delivery_status'), table_name='order_delivery_details')
    op.drop_table('order_delivery_details')
    op.drop_index(op.f('ix_order_action_logs_order_id'), table_name='order_action_logs')
    op.drop_table('order_action_logs')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_orders_source'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_by_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_business_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_business_contact_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_carts_source'), table_name='carts')
    op.drop_index(op.f('ix_carts_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_business_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_business_contact_id'), table_name='carts')
    op.drop_table('carts')
    # ### end Alembic commands ###
