"""Update Contact Models and Table

Revision ID: 8e3053c90364
Revises: ec153a4b80f5
Create Date: 2025-07-08 08:34:11.240768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e3053c90364'
down_revision: Union[str, None] = 'ec153a4b80f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_dynamic', sa.Boolean(), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_business_id'), 'groups', ['business_id'], unique=False)
    op.create_table('group_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_contact_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_contact_id'], ['business_contacts.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_contact_id', 'group_id', name='_unique_group_contact')
    )
    op.add_column('business_contact_tags', sa.Column('assigned_by', sa.Integer(), nullable=True))
    op.add_column('business_contact_tags', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'business_contact_tags', 'users', ['assigned_by'], ['id'])
    op.add_column('business_contacts', sa.Column('sponsor_id', sa.UUID(), nullable=True))
    op.add_column('business_contacts', sa.Column('managed_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'business_contacts', 'users', ['managed_by_user_id'], ['id'])
    op.create_foreign_key(None, 'business_contacts', 'business_contacts', ['sponsor_id'], ['id'])
    op.drop_column('business_contacts', 'tags_json')
    op.add_column('contacts', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('isd_code', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('country_code', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('preferred_language', sa.String(), nullable=True))
    op.drop_column('contacts', 'full_name')
    op.add_column('tags', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('tags', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'tags', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'updated_at')
    op.drop_column('tags', 'created_by')
    op.add_column('contacts', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('contacts', 'preferred_language')
    op.drop_column('contacts', 'gender')
    op.drop_column('contacts', 'country_code')
    op.drop_column('contacts', 'isd_code')
    op.drop_column('contacts', 'last_name')
    op.drop_column('contacts', 'first_name')
    op.add_column('business_contacts', sa.Column('tags_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'business_contacts', type_='foreignkey')
    op.drop_constraint(None, 'business_contacts', type_='foreignkey')
    op.drop_column('business_contacts', 'managed_by_user_id')
    op.drop_column('business_contacts', 'sponsor_id')
    op.drop_constraint(None, 'business_contact_tags', type_='foreignkey')
    op.drop_column('business_contact_tags', 'assigned_at')
    op.drop_column('business_contact_tags', 'assigned_by')
    op.drop_table('group_contacts')
    op.drop_index(op.f('ix_groups_business_id'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
