"""Add Images Column

Revision ID: 8feb0b030ac0
Revises: b33627bee91a
Create Date: 2025-06-12 23:55:36.304449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8feb0b030ac0'
down_revision: Union[str, None] = 'b33627bee91a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('favicon', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    op.drop_column('businesses', 'favicon')
    op.drop_column('businesses', 'image_url')
    # ### end Alembic commands ###
