"""Product Image Update

Revision ID: 9a0d053a2553
Revises: a267b8d7eabe
Create Date: 2025-07-02 19:41:15.842635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a0d053a2553'
down_revision: Union[str, None] = 'a267b8d7eabe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('product_id', sa.Integer(), nullable=True))
    op.alter_column('product_images', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'product_images', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.alter_column('product_images', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('product_images', 'product_id')
    # ### end Alembic commands ###
