"""Update Oder Module

Revision ID: 9b42fd14d8b6
Revises: 460bcbb9df4e
Create Date: 2025-07-29 00:01:56.065760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b42fd14d8b6'
down_revision: Union[str, None] = '460bcbb9df4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('allow_coupon', sa.Boolean(), nullable=True))
    op.drop_column('offers', 'can_stack_with_coupon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('can_stack_with_coupon', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('offers', 'allow_coupon')
    # ### end Alembic commands ###
