"""Update Service Tables

Revision ID: 9f8c7edbb44a
Revises: 57485a7c181b
Create Date: 2025-07-28 19:57:29.049627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f8c7edbb44a'
down_revision: Union[str, None] = '57485a7c181b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Service name/title'),
    sa.Column('description', sa.String(length=2000), nullable=False, comment='Detailed service description'),
    sa.Column('cancellation_policy', sa.String(length=1000), nullable=True, comment='Cancellation terms for the service'),
    sa.Column('image_url', sa.Text(), nullable=True, comment='Single image URL representing the service'),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='Owning business ID'),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True, comment='Creator/admin user ID'),
    sa.Column('parent_service_id', sa.Integer(), nullable=True, comment='If this service is tied to a service (optional)'),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_path', sa.ARRAY(sa.Integer()), nullable=True, comment='Full subcategory path as list of IDs'),
    sa.Column('price', sa.Numeric(), nullable=False, comment='Base price of the service'),
    sa.Column('discount_type', sa.String(length=20), nullable=True, comment="'percentage' or 'flat'"),
    sa.Column('discount_value', sa.Numeric(), nullable=True),
    sa.Column('max_discount', sa.Numeric(), nullable=True),
    sa.Column('include_tax', sa.Boolean(), nullable=True, comment='If true, tax is included in price'),
    sa.Column('tax_rate', sa.Numeric(), nullable=True, comment='Applicable tax rate in percentage (e.g., 18 for 18%)'),
    sa.Column('location_type', sa.Enum('ONSITE', 'ONLINE', 'CUSTOMER_LOCATION', name='locationtype'), nullable=True, comment='onsite | online | customer_location'),
    sa.Column('is_online', sa.Boolean(), nullable=True, comment='If true, this service shows on platform'),
    sa.Column('capacity', sa.Integer(), nullable=True, comment='Maximum number of participants/bookings'),
    sa.Column('booking_required', sa.Boolean(), nullable=True, comment='If true, booking is required'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='Total duration of the service in minutes'),
    sa.Column('schedule_type', sa.Enum('TIME_SLOT', 'FIXED', 'DURATION', 'SUBSCRIPTION', 'FLEXIBLE', name='scheduletype'), nullable=True, comment='time_slot | fixed | duration | subscription | flexible'),
    sa.Column('days_of_week', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Days service is available, e.g. ['Monday', 'Wednesday']"),
    sa.Column('start_time', sa.String(length=10), nullable=True, comment="Start of daily slot availability/Fixed timing (e.g. '10:00')"),
    sa.Column('end_time', sa.String(length=10), nullable=True, comment="End of daily slot availability/Fixed timing (e.g. '22:00')"),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True, comment='Service start date'),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True, comment='Service end date'),
    sa.Column('buffer_time_before', sa.Integer(), nullable=True, comment='Buffer/setup time before service starts (in minutes)'),
    sa.Column('buffer_time_after', sa.Integer(), nullable=True, comment='Buffer/cleanup time after service ends (in minutes)'),
    sa.Column('lead_time', sa.Integer(), nullable=True, comment='Minimum advance time required for booking (in minutes)'),
    sa.Column('recurring', sa.Boolean(), nullable=True, comment='True if schedule is recurring (e.g. weekly yoga)'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Searchable tags for discovery'),
    sa.Column('is_featured', sa.Boolean(), nullable=True, comment='If true, highlights this service on platform'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='True if service is currently active'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
