"""Initial migration

Revision ID: ab814e1a19dd
Revises: 8eb4d21a5e91
Create Date: 2025-08-07 11:46:27.892608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab814e1a19dd'
down_revision: Union[str, None] = '8eb4d21a5e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'isd_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('businesses', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('businesses', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('cart_items', sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('cart_items', sa.Column('date', sa.Date(), nullable=True))
    op.drop_column('cart_items', 'day')
    op.drop_column('cart_items', 'start_date')
    op.drop_column('cart_items', 'time_slot')
    op.drop_column('order_payments', 'receipt_url')
    op.add_column('orders', sa.Column('item_discount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'item_discount')
    op.add_column('order_payments', sa.Column('receipt_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cart_items', sa.Column('time_slot', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cart_items', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('cart_items', sa.Column('day', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('cart_items', 'date')
    op.drop_column('cart_items', 'tax_percentage')
    op.alter_column('businesses', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('businesses', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('businesses', 'isd_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
