"""Add Lead Option

Revision ID: ac1b7d5c8fb1
Revises: ee278944c35b
Create Date: 2026-02-09 11:57:53.500433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1b7d5c8fb1'
down_revision: Union[str, None] = 'ee278944c35b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('import_type', sa.String(), nullable=False),
    sa.Column('unique_field', sa.String(), nullable=True),
    sa.Column('assign_group_ids', sa.JSON(), nullable=True),
    sa.Column('assign_tag_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('processed_rows', sa.Integer(), nullable=True),
    sa.Column('success_rows', sa.Integer(), nullable=True),
    sa.Column('failed_rows', sa.Integer(), nullable=True),
    sa.Column('error_file_path', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('business_contact_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_contact_id'], ['business_contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leads_assigned_status', 'leads', ['assigned_to', 'status'], unique=False)
    op.create_index('idx_leads_business_status', 'leads', ['business_id', 'status'], unique=False)
    op.create_index(op.f('ix_leads_business_id'), 'leads', ['business_id'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_phone_number'), 'leads', ['phone_number'], unique=False)
    op.create_index(op.f('ix_leads_source'), 'leads', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_source'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone_number'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_business_id'), table_name='leads')
    op.drop_index('idx_leads_business_status', table_name='leads')
    op.drop_index('idx_leads_assigned_status', table_name='leads')
    op.drop_table('leads')
    op.drop_table('import_jobs')
    # ### end Alembic commands ###
