"""Update Business Table

Revision ID: b33627bee91a
Revises: d910f9083c67
Create Date: 2025-06-12 22:42:19.208871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33627bee91a'
down_revision: Union[str, None] = 'd910f9083c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'business_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'business_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
