"""Add Cart/Order Tables

Revision ID: b33ddeb879fb
Revises: 653dfe321252
Create Date: 2025-07-31 01:46:42.421665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33ddeb879fb'
down_revision: Union[str, None] = '653dfe321252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('applied_offer_id', sa.Integer(), nullable=True))
    op.add_column('cart_items', sa.Column('applied_coupon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart_items', 'coupons', ['applied_coupon_id'], ['id'])
    op.create_foreign_key(None, 'cart_items', 'offers', ['applied_offer_id'], ['id'])
    op.add_column('carts', sa.Column('coupon_id', sa.Integer(), nullable=True))
    op.add_column('carts', sa.Column('coupon_discount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('carts', sa.Column('offer_id', sa.Integer(), nullable=True))
    op.add_column('carts', sa.Column('offer_discount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_foreign_key(None, 'carts', 'offers', ['offer_id'], ['id'])
    op.create_foreign_key(None, 'carts', 'coupons', ['coupon_id'], ['id'])
    op.add_column('orders', sa.Column('coupon_discount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('offer_discount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('additional_discount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('handling_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('orders', 'discount_total')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('discount_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('orders', 'handling_fee')
    op.drop_column('orders', 'delivery_fee')
    op.drop_column('orders', 'additional_discount')
    op.drop_column('orders', 'offer_discount')
    op.drop_column('orders', 'coupon_discount')
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_column('carts', 'offer_discount')
    op.drop_column('carts', 'offer_id')
    op.drop_column('carts', 'coupon_discount')
    op.drop_column('carts', 'coupon_id')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_column('cart_items', 'applied_coupon_id')
    op.drop_column('cart_items', 'applied_offer_id')
    # ### end Alembic commands ###
