"""Update DB User 

Revision ID: b89c4928c1fe
Revises: b7b5e78341ec
Create Date: 2025-07-15 22:30:46.342243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b89c4928c1fe'
down_revision: Union[str, None] = 'b7b5e78341ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'referral_code',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['referral_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'referral_code',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    # ### end Alembic commands ###
