"""Add User Payment Table

Revision ID: bbee5d81691e
Revises: b89c4928c1fe
Create Date: 2025-07-15 22:56:39.440850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbee5d81691e'
down_revision: Union[str, None] = 'b89c4928c1fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('receipt', sa.String(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'SUCCESS', 'FAILED', 'REFUNDED', 'PENDING', name='paymentstatus'), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id')
    )
    op.alter_column('users', 'referral_code',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['referral_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'referral_code',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.drop_table('user_payments')
    # ### end Alembic commands ###
