"""Update Contact Models and Table

Revision ID: bfbfc1889e9b
Revises: 18adaded97c9
Create Date: 2025-07-11 00:55:22.836151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfbfc1889e9b'
down_revision: Union[str, None] = '18adaded97c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_business_contact_tag_tag_id', table_name='business_contact_tags')
    op.drop_index('idx_contacts_business_created', table_name='business_contacts')
    op.drop_index('idx_contacts_business_id', table_name='business_contacts')
    op.drop_index('idx_contacts_created_at', table_name='business_contacts')
    op.drop_index('idx_contacts_user_id', table_name='business_contacts')
    op.drop_index('idx_group_contacts_group_id', table_name='group_contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_group_contacts_group_id', 'group_contacts', ['group_id'], unique=False)
    op.create_index('idx_contacts_user_id', 'business_contacts', ['managed_by_user_id'], unique=False)
    op.create_index('idx_contacts_created_at', 'business_contacts', ['created_at'], unique=False)
    op.create_index('idx_contacts_business_id', 'business_contacts', ['business_id'], unique=False)
    op.create_index('idx_contacts_business_created', 'business_contacts', ['business_id', 'created_at'], unique=False)
    op.create_index('idx_business_contact_tag_tag_id', 'business_contact_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###
