"""Add Whatsapp Webhook

Revision ID: c258004c1fe2
Revises: bd041abea814
Create Date: 2025-08-20 18:02:13.788292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c258004c1fe2'
down_revision: Union[str, None] = 'bd041abea814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_messages_event_type'), 'webhook_messages', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_messages_id'), 'webhook_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_messages_id'), table_name='webhook_messages')
    op.drop_index(op.f('ix_webhook_messages_event_type'), table_name='webhook_messages')
    op.drop_table('webhook_messages')
    # ### end Alembic commands ###
