"""Update Supplier Models

Revision ID: c3293678ebd2
Revises: 222cb81c4a57
Create Date: 2025-08-08 20:30:29.283435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3293678ebd2'
down_revision: Union[str, None] = '222cb81c4a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_purchase_items', sa.Column('product_id', sa.Integer(), nullable=False))
    op.alter_column('supplier_purchase_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_column('supplier_purchase_items', 'description')
    op.add_column('supplier_purchases', sa.Column('purchase_number', sa.String(length=255), nullable=False))
    op.add_column('supplier_purchases', sa.Column('tax_rate', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('supplier_purchases', 'taxable_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('supplier_purchases', 'total_tax_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('supplier_purchases', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('supplier_purchases', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('supplier_purchases', 'total_tax_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('supplier_purchases', 'taxable_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_column('supplier_purchases', 'tax_rate')
    op.drop_column('supplier_purchases', 'purchase_number')
    op.add_column('supplier_purchase_items', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('supplier_purchase_items', 'quantity',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('supplier_purchase_items', 'product_id')
    # ### end Alembic commands ###
