"""Update Product Table Structure

Revision ID: d6048761b845
Revises: 70f880275cdc
Create Date: 2025-07-22 20:27:47.659672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6048761b845'
down_revision: Union[str, None] = '70f880275cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_custom_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_type', sa.String(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_filterable', sa.Boolean(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_custom_fields_business_id'), 'product_custom_fields', ['business_id'], unique=False)
    op.create_index(op.f('ix_product_custom_fields_id'), 'product_custom_fields', ['id'], unique=False)
    op.create_table('product_master_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('base_unit', 'package_type', 'brand', 'manufacturer', name='master_type'), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_custom_field_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['product_custom_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_custom_field_values_id'), 'product_custom_field_values', ['id'], unique=False)
    op.drop_column('product_images', 'variant_id')
    op.drop_column('product_images', 'is_primary')
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=False))
    op.add_column('products', sa.Column('is_product_variant', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('parent_product_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('subcategory_path', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('products', sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('discount_type', sa.String(), nullable=True))
    op.add_column('products', sa.Column('discount_value', sa.Numeric(), nullable=True))
    op.add_column('products', sa.Column('max_discount', sa.Numeric(), nullable=True))
    op.add_column('products', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('products', sa.Column('hsn_code', sa.String(length=10), nullable=True))
    op.add_column('products', sa.Column('package_type', sa.String(length=50), nullable=False))
    op.add_column('products', sa.Column('stock_qty', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('low_stock_alert', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('manufacturer', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('packed_date', sa.Date(), nullable=True))
    op.add_column('products', sa.Column('expiry_date', sa.Date(), nullable=True))
    op.add_column('products', sa.Column('is_online', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('barcode', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('qr_code', sa.String(), nullable=True))
    op.add_column('products', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.alter_column('products', 'description',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('products', 'base_unit',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_unique_constraint(None, 'products', ['slug'])
    op.create_unique_constraint(None, 'products', ['barcode'])
    op.drop_constraint('products_subcategory_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'products', ['parent_product_id'], ['id'])
    op.create_foreign_key(None, 'products', 'users', ['created_by_user_id'], ['id'])
    op.drop_column('products', 'tax_value')
    op.drop_column('products', 'tags')
    op.drop_column('products', 'subcategory_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('subcategory_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('tax_value', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_subcategory_id_fkey', 'products', 'categories', ['subcategory_id'], ['id'])
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.alter_column('products', 'sku',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('products', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('products', 'base_unit',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('products', 'created_by_user_id')
    op.drop_column('products', 'qr_code')
    op.drop_column('products', 'barcode')
    op.drop_column('products', 'slug')
    op.drop_column('products', 'is_online')
    op.drop_column('products', 'expiry_date')
    op.drop_column('products', 'packed_date')
    op.drop_column('products', 'manufacturer')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'low_stock_alert')
    op.drop_column('products', 'stock_qty')
    op.drop_column('products', 'package_type')
    op.drop_column('products', 'hsn_code')
    op.drop_column('products', 'tax_rate')
    op.drop_column('products', 'max_discount')
    op.drop_column('products', 'discount_value')
    op.drop_column('products', 'discount_type')
    op.drop_column('products', 'selling_price')
    op.drop_column('products', 'purchase_price')
    op.drop_column('products', 'subcategory_path')
    op.drop_column('products', 'parent_product_id')
    op.drop_column('products', 'is_product_variant')
    op.drop_column('products', 'image_url')
    op.add_column('product_images', sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('product_images', sa.Column('variant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('product_images_variant_id_fkey', 'product_images', 'product_variants', ['variant_id'], ['id'], ondelete='CASCADE')
    op.create_table('product_variants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('variant_name', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('min_qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('allowed_qty_steps', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('available_qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purchase_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('selling_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('discount_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('discount_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.CheckConstraint('available_qty >= 0', name='check_available_qty'),
    sa.CheckConstraint('max_qty > min_qty', name='check_max_qty'),
    sa.CheckConstraint('min_qty >= 0', name='check_min_qty'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_variants_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='product_variants_pkey')
    )
    op.create_index('ix_product_variants_id', 'product_variants', ['id'], unique=False)
    op.drop_index(op.f('ix_product_custom_field_values_id'), table_name='product_custom_field_values')
    op.drop_table('product_custom_field_values')
    op.drop_table('product_master_data')
    op.drop_index(op.f('ix_product_custom_fields_id'), table_name='product_custom_fields')
    op.drop_index(op.f('ix_product_custom_fields_business_id'), table_name='product_custom_fields')
    op.drop_table('product_custom_fields')
    # ### end Alembic commands ###
