"""Restructure Tables

Revision ID: d8f7e26c3cb8
Revises: df5a5cdb44d6
Create Date: 2025-07-04 21:52:45.625821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8f7e26c3cb8'
down_revision: Union[str, None] = 'df5a5cdb44d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('businesses_user_id_fkey', 'businesses', type_='foreignkey')
    op.drop_column('businesses', 'user_id')
    op.add_column('permissions', sa.Column('default_manager', sa.Boolean(), nullable=True))
    op.add_column('product_variants', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_constraint('product_variants_sku_key', 'product_variants', type_='unique')
    op.drop_column('product_variants', 'sku')
    op.drop_column('product_variants', 'color_or_flavor')
    op.drop_column('product_variants', 'size')
    op.drop_column('product_variants', 'barcode')
    op.drop_column('product_variants', 'package_type')
    op.add_column('users', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'businesses', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'business_id')
    op.add_column('product_variants', sa.Column('package_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('product_variants', sa.Column('barcode', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('product_variants', sa.Column('size', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('product_variants', sa.Column('color_or_flavor', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('product_variants', sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint('product_variants_sku_key', 'product_variants', ['sku'], postgresql_nulls_not_distinct=False)
    op.drop_column('product_variants', 'attributes')
    op.drop_column('permissions', 'default_manager')
    op.add_column('businesses', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('businesses_user_id_fkey', 'businesses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
