"""Add ENums columns

Revision ID: d910f9083c67
Revises: 9fe2cb2ff136
Create Date: 2025-06-12 20:27:37.957598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd910f9083c67'
down_revision: Union[str, None] = '9fe2cb2ff136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('business_type', sa.String(), nullable=True))
    op.add_column('permissions', sa.Column('type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'type')
    op.drop_column('businesses', 'business_type')
    # ### end Alembic commands ###
