"""Add User New Tables

Revision ID: da9277e973f6
Revises: 007b9930a65d
Create Date: 2025-07-15 23:40:00.067481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9277e973f6'
down_revision: Union[str, None] = '007b9930a65d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    payment_mode_enum = postgresql.ENUM('ONLINE', 'CASH', 'MANUAL', name='paymentmode')
    payment_mode_enum.create(op.get_bind())

    op.create_table('user_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(), nullable=True),
    sa.Column('original_amount', sa.Float(), nullable=False),
    sa.Column('offer_discount', sa.Float(), nullable=True),
    sa.Column('coupon_discount', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('gst_percent', sa.Float(), nullable=True),
    sa.Column('gst_amount', sa.Float(), nullable=False),
    sa.Column('final_amount', sa.Float(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='orderstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_payments', sa.Column('payment_mode', sa.Enum('ONLINE', 'CASH', 'MANUAL', name='paymentmode'), nullable=True))
    op.add_column('user_payments', sa.Column('payment_method', sa.String(), nullable=True))
    op.alter_column('user_payments', 'razorpay_order_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('user_payments_razorpay_order_id_key', 'user_payments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_payments_razorpay_order_id_key', 'user_payments', ['razorpay_order_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_payments', 'razorpay_order_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user_payments', 'payment_method')
    op.drop_column('user_payments', 'payment_mode')
    op.drop_table('user_orders')
    # ### end Alembic commands ###
