"""Update DB User 

Revision ID: de1dcbd92edf
Revises: 20304b0a7615
Create Date: 2025-07-15 22:18:47.341160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de1dcbd92edf'
down_revision: Union[str, None] = '20304b0a7615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parent_user_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('referral_code', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('referred_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['referred_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['parent_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referred_by')
    op.drop_column('users', 'referral_code')
    op.drop_column('users', 'parent_user_id')
    # ### end Alembic commands ###
