"""Service Tables Update

Revision ID: df5a5cdb44d6
Revises: 7414aac3a497
Create Date: 2025-07-04 18:17:05.024435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df5a5cdb44d6'
down_revision: Union[str, None] = '7414aac3a497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('discount_type', sa.String(), nullable=True))
    op.add_column('services', sa.Column('discount_value', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'discount_value')
    op.drop_column('services', 'discount_type')
    # ### end Alembic commands ###
