"""Add User New Plans

Revision ID: e16312c59bb2
Revises: 9df604726812
Create Date: 2025-07-16 00:21:26.360733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e16312c59bb2'
down_revision: Union[str, None] = '9df604726812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('offer_discount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'offer_discount')
    # ### end Alembic commands ###
