"""Restructure Tables

Revision ID: e2b04cebafc8
Revises: d8f7e26c3cb8
Create Date: 2025-07-04 21:53:50.512855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b04cebafc8'
down_revision: Union[str, None] = 'd8f7e26c3cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('discount_type', sa.String(), nullable=True))
    op.add_column('product_variants', sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'discount_value')
    op.drop_column('product_variants', 'discount_type')
    # ### end Alembic commands ###
