"""Remove Unique check from product image

Revision ID: e69f0951f55b
Revises: 172d974df748
Create Date: 2025-08-24 16:36:42.380140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69f0951f55b'
down_revision: Union[str, None] = '172d974df748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_image_url_key', 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('products_image_url_key', 'products', ['image_url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
