"""Add Service Table

Revision ID: f00794083c96
Revises: 5a8d852c11dc
Create Date: 2025-06-27 23:17:48.546707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f00794083c96'
down_revision: Union[str, None] = '5a8d852c11dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('services', 'subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
