"""Update user permissionsr

Revision ID: f2fb83c722d7
Revises: 0f084973f937
Create Date: 2025-07-16 22:57:10.362450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2fb83c722d7'
down_revision: Union[str, None] = '0f084973f937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('default_sales', sa.Boolean(), nullable=True))
    op.add_column('permissions', sa.Column('default_support', sa.Boolean(), nullable=True))
    op.add_column('permissions', sa.Column('default_platform_admin', sa.Boolean(), nullable=True))
    op.add_column('permissions', sa.Column('default_platform_employee', sa.Boolean(), nullable=True))
    op.add_column('permissions', sa.Column('default_developer', sa.Boolean(), nullable=True))
    op.add_column('permissions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('permissions', 'default_manager')
    op.add_column('user_permissions', sa.Column('permission_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_permissions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('user_permissions_permission_id_fkey', 'user_permissions', type_='foreignkey')
    op.drop_column('user_permissions', 'permission_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_permissions', sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_permissions_permission_id_fkey', 'user_permissions', 'permissions', ['permission_id'], ['id'])
    op.drop_column('user_permissions', 'updated_at')
    op.drop_column('user_permissions', 'permission_keys')
    op.add_column('permissions', sa.Column('default_manager', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('permissions', 'updated_at')
    op.drop_column('permissions', 'default_developer')
    op.drop_column('permissions', 'default_platform_employee')
    op.drop_column('permissions', 'default_platform_admin')
    op.drop_column('permissions', 'default_support')
    op.drop_column('permissions', 'default_sales')
    # ### end Alembic commands ###
