"""Update Cart/Order

Revision ID: fc0d4a2c2968
Revises: 60db0098bb75
Create Date: 2025-08-01 02:03:00.485869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0d4a2c2968'
down_revision: Union[str, None] = '60db0098bb75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_payments', sa.Column('is_manual_entry', sa.Boolean(), nullable=True))
    op.drop_constraint('uq_order_payment_order_id', 'order_payments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_order_payment_order_id', 'order_payments', ['order_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('order_payments', 'is_manual_entry')
    # ### end Alembic commands ###
